### PR TITLE
Stored procedures

### PR DESCRIPTION
**Pull request by suneduraan**
redoing the pull request. also changed int IDs to GUIDs

### CODE REVIEW

**Comment by Albrecht-Ohsiek** [comment]
Ok I'm leaving the ID on login as and INT for now since I believe you are using it for the API's. Further everything looks good. Just checking you added more stored procedures to the DB.mdf file. Do you have a script for adding them?

Further looks good. APPROVED.

**Comment by Albrecht-Ohsiek** [comment]
Either pick" Create a Merge Commit" or "Squash and Merge".

**Comment by Albrecht-Ohsiek** [comment]
Remember to delete the branch once it is merged in. Congrats on your first PR !!!

**Comment by suneduraan** [comment]
I did not save a script for the stored procedures but I will do so from now on. When i work on the crud operations again, do I have to create a new branch again and repeat what i just did?

**Pull request merged**
